# Generated by Django 6.0.2 on 2026-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_conversation_issaved_alter_document_tags'),
        ('api', '0006_alter_document_tags'),
    ]

    operations = [
    ]
