# Generated by Django 6.0.2 on 2026-08-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20260830_1339'),
        ('api', '0007_merge_20260830_1445'),
    ]

    operations = [
    ]
